[build]
publish = "./"
command = ""  # No build command needed for static files

[[redirects]]
  from = "/"
  to = "/main/index.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog-content/blog.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/blog-content/about.html"
  status = 200

[[redirects]]
  from = "https://blog.hackwith.me"
  to = "/blog-content/blog.html"
  status = 200

[[redirects]]
  from = "https://blog.hackwith.me/about"
  to = "/blog-content/about.html"
  status = 200

[[redirects]]
  from = "https://blog.hackwith.me/*"
  to = "/blog-content/:splat"
  status = 200

[[redirects]]
  from = "http://hackwith.me/*"
  to = "https://hackwith.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://blog.hackwith.me/*"
  to = "https://blog.hackwith.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/shared/404.html"
  status = 404

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app *.hackwith.me cdnjs.cloudflare.com;"
