[build]
publish = "/"
command = ""  # No build command needed for static files

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog-content/blog.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/blog-content/about.html"
  status = 200

[[redirects]]
  from = "/blog-content/posts/*"
  to = "/blog-content/post.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog-content/tags"
  to = "/blog-content/tags.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/shared/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https:; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https: cdn.jsdelivr.net cdnjs.cloudflare.com; 
      style-src 'self' 'unsafe-inline' https: cdnjs.cloudflare.com; 
      img-src 'self' data: https:; 
      font-src 'self' https: cdnjs.cloudflare.com; 
      connect-src 'self' https:; 
      media-src 'self' https:; 
      object-src 'none';
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      """

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.md"
  [headers.values]
    Content-Type = "text/markdown"
