[build]
publish = "./"
command = ""  # No build command needed for static files

[[redirects]]
  from = "/"
  to = "/main/index.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog-content/blog.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/blog-content/about.html"
  status = 200

[[redirects]]
  from = "https://blog.hackwith.me"
  to = "/blog-content/blog.html"
  status = 200

[[redirects]]
  from = "https://blog.hackwith.me/about"
  to = "/blog-content/about.html"
  status = 200

[[redirects]]
  from = "https://blog.hackwith.me/*"
  to = "/blog-content/:splat"
  status = 200

[[redirects]]
  from = "http://hackwith.me/*"
  to = "https://hackwith.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://blog.hackwith.me/*"
  to = "https://blog.hackwith.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/shared/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://ka-f.fontawesome.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
